# dummy edit to trigger build
#dist: trusty
#sudo: false

language: python

python:
    - "2.7"

services:
    - postgresql

addons:
    postgresql: "9.4"

env: 
    - TEST_AIIDA_BACKEND=django
    - TEST_AIIDA_BACKEND=sqlalchemy

install:
    - pip install -U pip wheel setuptools
    - pip install .[tests]

before_script:
    - psql -c "CREATE DATABASE $TEST_AIIDA_BACKEND;" -U postgres
    - psql -c "CREATE DATABASE test_$TEST_AIIDA_BACKEND;" -U postgres
    - verdi -p $TEST_AIIDA_BACKEND setup --non-interactive --backend=$TEST_AIIDA_BACKEND --email="aiida@localhost" --db_host="localhost" --db_port=5432 --db_name="$TEST_AIIDA_BACKEND" --db_user=postgres --db_pass='' --repo="/tmp/test_repository_${TEST_AIIDA_BACKEND}/" --first-name=AiiDA --last-name=test --institution="AiiDA Team" --no-password

script: py.test
